version: '2'

services:
  pgp:
    build: .
    ports:
      - '8000:80'
      - '9999:9999'
    networks:
      - pgpool
    volumes:
      - ./logs/pgpool:/var/log/pgpool
      - ./logs/apache2:/var/log/apache2
      - ./config/pgmgt.conf.php:/var/www/html/admin-tool/conf/pgmgt.conf.php
      - ./config/etc:/usr/local/etc
    env_file:
      - '.environment'

networks:
  pgpool:
