version: '2'

services:
  pgp:
    build: .
    ports:
      - '8000:80'
      - '9999:9999'
    networks:
      - pgpool
    volumes:
      - ./logs:/var/log/pgpool
      - ./config/pgmgt.conf.php:/var/www/html/admin-tool/conf/pgmgt.conf.php
      - ./config/etc:/usr/local/etc
#      - ./config/pool_hba.conf:/usr/local/etc/pool_hba.conf
#      - ./config/pgpool.conf:/usr/local/etc/pgpool.conf
    env_file:
      - '.environment'

networks:
  pgpool:
